const images = {
  star_2: require('./../assets/images/star_2.png'),
  star: require('./../assets/images/star.png'),
  search: require('../assets/images/search.png'),
  bookmark: require('../assets/images/bookmark.png'),
  down: require('../assets/images/down.png'),
  cross: require('../assets/images/cross.png'),
  back: require('../assets/images/backArrow.png'),
  cross: require('../assets/images/cross.png'),
  camera: require('../assets/images/camera.png'),
  chat: require('../assets/images/chat.png'),
  customer: require('../assets/images/customer.png'),
  filter: require('../assets/images/filter.png'),
  frame: require('../assets/images/frame.png'),
  location: require('../assets/images/location.png'),
  menu: require('../assets/images/menu.png'),
  vender: require('../assets/images/vender.png'),
  welcome: require('../assets/images/welcome.png'),
  option: require('../assets/images/option.png'),
  plus: require('../assets/images/plus.png'),
  bike: require('../assets/images/bike.png'),
  minus: require('../assets/images/minus.png'),
  rating: require('../assets/images/rating.png'),
  heart: require('../assets/images/heart.png'),
};
export default images;
